### ISSUE TITLE
connection.add gives endless operations

### ISSUE THREAD

**Issue by TcaManager** [cfelder/ldap3-orm#1]
Hi, Some problem here, looks like one method makes infinite loop or waits for a response that never comes, here is the code, did I forget something?
```python
from ldap3_orm import EntryType
from ldap3_orm.config import config
from ldap3_orm.connection import conn

FrEduCtUser = EntryType(
    'uid={uid},'+ config.base_dn,
    ['person','organizationalPerson','inetOrgPerson','FrEduCtPerson'], 
    conn
)
```
```python
class FrEduCtLdapSession(object):
    connection = conn
    
    def getObjectClassesAndAttributes(self,entry):
        attributes = entry.entry_attributes_as_dict
        object_classes = attributes['objectClass']
        del attributes['objectClass']
        return object_classes,attributes
    
    def addUser(self,user):
        object_classes,attributes = self.getObjectClassesAndAttributes(user)
        return self.connection.add(
            user.entry_dn, 
            object_classes,
            attributes
        )
```
```python
from I2HM_Console import FrEduCtUser, FrEduCtPolicy, FrEduCtLdapSession
from ldap3 import HASHED_SALTED_SHA
from ldap3.utils.hashed import hashed

session = FrEduCtLdapSession()

bozo = FrEduCtUser(
    uid='bleclown',
    givenName='Bozo',
    sn='Le Clown',
    cn='Bozo Le Clown',
    userPassword=hashed(HASHED_SALTED_SHA, 'Ohlalalala')
)

b1 = session.addUser(bozo)
```

```bash
Traceback (most recent call last):

  File "<ipython-input-24-10fcec10856d>", line 1, in <module>
    runfile('/home/julien/WorkSpace/LDAP/LdapConsole/test.py', wdir='/home/julien/WorkSpace/LDAP/LdapConsole')

  File "/home/julien/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/home/julien/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/julien/WorkSpace/LDAP/LdapConsole/test.py", line 24, in <module>
    b1 = session.addUser(bozo)

  File "/home/julien/WorkSpace/LDAP/LdapConsole/I2HM_Console/tools/session.py", line 19, in addUser
    attributes

  File "/home/julien/anaconda3/lib/python3.7/site-packages/ldap3/core/connection.py", line 936, in add
    response = self.post_send_single_response(self.send('addRequest', request, controls))

  File "/home/julien/anaconda3/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 121, in post_send_single_response
    responses, result = self.get_response(message_id)

  File "/home/julien/anaconda3/lib/python3.7/site-packages/ldap3/strategy/base.py", line 325, in get_response
    responses = self._get_response(message_id)

  File "/home/julien/anaconda3/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 157, in _get_response
    responses = self.receiving()

  File "/home/julien/anaconda3/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 82, in receiving
    data = self.connection.socket.recv(self.socket_size)
```

**Comment by cfelder** [comment]
Thanks for reaching out @TcaManager. I've modified and tested your code on my personal ldap server without using objectClass ``FrEduCtPerson`` because I don't have the corresponding schema on my server. It works fine though.

In order to pin point the problem on your system can you please add some logging configuration at the top:

```python
import logging
from ldap3.utils import log

logging.basicConfig(level=logging.CRITICAL)
log.set_library_log_activation_level(logging.CRITICAL)
```

and add the following line before ``b1 = session.addUser(bozo)``:
```python
log.set_library_log_detail_level(log.NETWORK)
```

This will log all information to level CRITICAL just for the ``add`` call.

Best
Christian

**Comment by TcaManager** [comment]
My default config file
```python
url = 'ldap://id-devops-7.in.ac-orleans-tours.fr:12101'
base_dn = 'ou=people,dc=educt'
username = 'cn=****************'
password = '*********'

modules = [
    '~/WorkSpace/LDAP/LdapConsole/I2HMConsole/models/ldap/user.py',
    '~/WorkSpace/LDAP/LdapConsole/I2HMConsole/models/ldap/policy.py'
]

pythonpaths = [
   '~/WorkSpace/LDAP/LdapConsole/I2HMConsole/tools'
]

connconfig = {
    'client_strategy': 'STRATEGY_SYNC_RESTARTABLE'
}
```
My script
```python
import logging
logging.basicConfig(filename='client_application.log', level=logging.CRITICAL)
from ldap3.utils.log import set_library_log_activation_level,set_library_log_detail_level, OFF, BASIC, NETWORK, EXTENDED
set_library_log_activation_level(logging.CRITICAL)  # ldap3 will emit its log only when you set level=logging.CRITICAL in your log configuration
set_library_log_detail_level(EXTENDED)

from I2HMConsole import FrEduCtPolicy,FrEduCtUser
from ldap3 import HASHED_SALTED_SHA
from ldap3.utils.hashed import hashed
from ldap3_orm.basic import add,search,delete

bozo = FrEduCtUser(
    uid='bleclown',
    givenName='Bozo',
    sn='Le Clown',
    cn='Bozo Le Clown',
    userPassword=hashed(HASHED_SALTED_SHA, 'Ohlalalala')
)

agathe = FrEduCtUser(
    uid='atheblues',
    givenName='Agathe',
    sn='The Blues',
    cn='Agathe The Blues',
    userPassword=hashed(HASHED_SALTED_SHA, 'OhYeah!')
)

add(bozo)
add(agathe)
```
I changed the code to use add, search and delete. I also deleted the connconfig part in default file. I restarted the Ldap server. Now I have another problem
`socket sending error[Errno 32] Broken pipe`
Should I open another issue? I checked ldapsearch and it works with the same data.
I get this in the log
```bash
>
CRITICAL:ldap3:BASIC:start ADD operation via <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:EXTENDED:dn sanitized to <uid=bleclown,ou=people,dc=educt> for ADD operation via <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:PROTOCOL:ADD request <{'entry': 'uid=bleclown,ou=people,dc=educt', 'attributes': {'objectClass': ['person', 'organizationalPerson', 'inetOrgPerson', 'FrEduCtPerson'], 'uid': ['bleclown'], 'givenName': ['Bozo'], 'sn': ['Le Clown'], 'cn': ['Bozo Le Clown'], 'userPassword': ['{ssha}BsAlBJeCGB6qDAuxT6k3oUa46hqBIYQyZJyVjg==']}}> sent via <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:PROTOCOL:new message id <31> generated
CRITICAL:ldap3:NETWORK:sending 1 ldap message for <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:ERROR:<socket sending error[Errno 32] Broken pipe> for <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:ERROR:detail level set to EXTENDED
CRITICAL:ldap3:BASIC:instantiated AttrDef: <objectClass - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <sn - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <cn - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <description - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <seeAlso - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <telephoneNumber - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <userPassword - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <objectClass - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <sn - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <cn - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <destinationIndicator - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <facsimileTelephoneNumber - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <internationaliSDNNumber - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <l - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <ou - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <physicalDeliveryOfficeName - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <postOfficeBox - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <postalAddress - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <postalCode - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <preferredDeliveryMethod - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <registeredAddress - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <st - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <street - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <teletexTerminalIdentifier - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <telexNumber - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <title - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <x121Address - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <objectClass - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <sn - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <cn - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <audio - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <businessCategory - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <carLicense - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <departmentNumber - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <displayName - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <employeeType - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <employeeNumber - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <givenName - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <homePhone - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <homePostalAddress - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <initials - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <jpegPhoto - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <labeledUri - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <manager - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <mobile - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pager - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <photo - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <preferredLanguage - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <mail - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <o - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <roomNumber - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <secretary - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <uid - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <x500UniqueIdentifier - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <userCertificate - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <userSMIMECertificate - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <userPKCS12 - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <uid - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <FrEduCtPersonTargetedID - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated ObjectDef: <OBJ : person, organizationalPerson, inetOrgPerson, FrEduCtPerson
AUX : <None>
OID: person (Structural) 2.5.6.6, top (Abstract) 2.5.6.0, organizationalPerson (Structural) 2.5.6.7, person (Structural) 2.5.6.6, top (Abstract) 2.5.6.0, inetOrgPerson (Structural) 2.16.840.1.113730.3.2.2, organizationalPerson (Structural) 2.5.6.7, person (Structural) 2.5.6.6, top (Abstract) 2.5.6.0, FrEduCtPerson (Structural) 1.3.6.1.4.1.20326.10.999.999.10
MUST: cn, objectClass, sn
MAY : FrEduCtPersonTargetedID, audio, businessCategory, carLicense, departmentNumber, description, destinationIndicator, displayName, employeeNumber, employeeType, facsimileTelephoneNumber, givenName, homePhone, homePostalAddress, initials, internationaliSDNNumber, jpegPhoto, l, labeledUri, mail, manager, mobile, o, ou, pager, photo, physicalDeliveryOfficeName, postOfficeBox, postalAddress, postalCode, preferredDeliveryMethod, preferredLanguage, registeredAddress, roomNumber, secretary, seeAlso, st, street, telephoneNumber, teletexTerminalIdentifier, telexNumber, title, uid, userCertificate, userPKCS12, userPassword, userSMIMECertificate, x121Address, x500UniqueIdentifier
>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <objectClass - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdAttribute - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdMinAge - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdMaxAge - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdInHistory - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdCheckQuality - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdMinLength - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdExpireWarning - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdGraceAuthNLimit - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdLockout - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdLockoutDuration - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdMaxFailure - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdFailureCountInterval - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdMustChange - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdAllowUserChange - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdSafeModify - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <objectClass - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdAttribute - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <cn - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <description - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <passwordRootdnMayBypassModsChecks - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <passwordStorageScheme - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdIsLockoutPrioritized - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <pwdKeepLastAuthTime - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated AttrDef: <objectClass - mandatory: False>
CRITICAL:ldap3:BASIC:instantiated ObjectDef: <OBJ : pwdPolicy, sunPwdPolicy, ldapSubEntry
AUX : <None>
OID: pwdPolicy (Auxiliary) 1.3.6.1.4.1.42.2.27.8.2.1, top (Abstract) 2.5.6.0, sunPwdPolicy (Auxiliary) 1.3.6.1.4.1.42.2.27.9.2.119, pwdPolicy (Auxiliary) 1.3.6.1.4.1.42.2.27.8.2.1, top (Abstract) 2.5.6.0, ldapSubEntry (Structural) 2.16.840.1.113719.2.142.6.1.1, top (Abstract) 2.5.6.0
MUST: cn, objectClass, pwdAttribute
MAY : description, passwordRootdnMayBypassModsChecks, passwordStorageScheme, pwdAllowUserChange, pwdCheckQuality, pwdExpireWarning, pwdFailureCountInterval, pwdGraceAuthNLimit, pwdInHistory, pwdIsLockoutPrioritized, pwdKeepLastAuthTime, pwdLockout, pwdLockoutDuration, pwdMaxAge, pwdMaxFailure, pwdMinAge, pwdMinLength, pwdMustChange, pwdSafeModify
>
CRITICAL:ldap3:BASIC:start ADD operation via <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:EXTENDED:dn sanitized to <uid=bleclown,ou=people,dc=educt> for ADD operation via <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:PROTOCOL:ADD request <{'entry': 'uid=bleclown,ou=people,dc=educt', 'attributes': {'objectClass': ['person', 'organizationalPerson', 'inetOrgPerson', 'FrEduCtPerson'], 'uid': ['bleclown'], 'givenName': ['Bozo'], 'sn': ['Le Clown'], 'cn': ['Bozo Le Clown'], 'userPassword': ['{ssha}L62c9c9e6yQuQ3aXsRapN7ANNBB0N7eN6MBzOA==']}}> sent via <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:PROTOCOL:new message id <32> generated
CRITICAL:ldap3:NETWORK:sending 1 ldap message for <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:ERROR:<socket sending error[Errno 32] Broken pipe> for <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:45800 - remote: [None]:None> - tls not started - listening - SyncStrategy - internal decoder>
```

**Comment by TcaManager** [comment]
After restarting my computer, I get different message in log
```bash
{'controls': None,
<< 'messageID': 5,
<< 'payload': [(0, False, 10, 50),
<<             (0, False, 4, b''),
<<             (0,
<<              False,
<<              4,
<<              b"Insufficient 'add' privilege to add the entry 'uid=atheblues"
<<              b",ou=people,dc=educt'.")],
<< 'protocolOp': 9}
CRITICAL:ldap3:PROTOCOL:ADD response <[{'result': 50, 'description': 'insufficientAccessRights', 'dn': '', 'message': "Insufficient 'add' privilege to add the entry 'uid=atheblues,ou=people,dc=educt'.", 'referrals': None, 'type': 'addResponse'}]> received via <ldap://id-devops-7.in.ac-orleans-tours.fr:12101 - cleartext - user: None - not lazy - bound - open - <local: 172.30.146.185:43370 - remote: 172.30.159.116:12101> - tls not started - listening - SyncStrategy - internal decoder>
CRITICAL:ldap3:BASIC:done ADD operation, result <False>
```
I checked many times the username and the url, is my config file incorrect?

**Comment by cfelder** [comment]
Hi TcaManager,

this is a bug in the configuration module.

``username`` and ``password`` are populated when using ``ldap3-ipython`` whereas the config module does not update the ``connconfig`` which is used to create the connection when using the ``ldap3_orm`` modules directly.

I'll change the config module to handle this properly.

Meanwhile can you please add ``user`` and ``password`` to your ``connconfig`` dictionary:
```python
connconfig = dict(
    user = 'cn=****************',
    password = '*********',
)
```

Furthermore ``STRATEGY_SYNC_RESTARTABLE`` has been renamed to just ``RESTARTABLE`` upstream in ldap3 v2.

Best
Christian

**Comment by TcaManager** [comment]
Thanks a lot, I changed it, the infinite loop is back, after many failures I get a timeout.

**Comment by TcaManager** [comment]
It's not a loop, it's just endless wait.

**Comment by cfelder** [comment]
Can you perform a search operation now?

For the add operation can you just move the following logging statement from your header just in front of the add operation to catch just all log output regarding the add operation?

```python
set_library_log_activation_level(logging.CRITICAL)
```

**Comment by TcaManager** [comment]
I changed my mind, I overrided basic, config, connection and conn objects, and now everything works perfectly fine, so I'll keep it that way. I close the issue but feel free to re-open it if you need to. Thanks a lot for your help, have a nice day (I may ask you a merge request in a few months).

**Comment by cfelder** [comment]
Thanks again for reaching out. It would be nice to know how you resolved the problem. I am also happy to review your merge request in the future.
